steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:uat', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}:uat']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'uat-web',
        '--image',
        'gcr.io/$PROJECT_ID/${_APP_NAME}:uat',
        '--platform',
        'managed',
        '--region',
        '${_REGION}',
        '--allow-unauthenticated',
      ]
images:
  - gcr.io/$PROJECT_ID/${_APP_NAME}:uat
timeout: 1200s
